name: autistock
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  share_plus: ^7.2.2
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.2
  provider: ^6.1.2
  fl_chart: ^0.66.2
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  intl: ^0.20.2
  table_calendar: ^3.0.9
  url_launcher: ^6.2.5
  image_picker: ^1.0.7
  audioplayers: ^6.0.0 # <-- Paquete añadido

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
