name: autistock
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  table_calendar: ^3.1.2
  audioplayers: ^5.2.1
  shared_preferences: ^2.2.3
  provider: ^6.1.2
  fl_chart: ^1.0.0
  flutter_local_notifications: ^19.4.1
  flutter_timezone: ^4.1.1
  path_provider: ^2.1.3
  permission_handler: ^12.0.1
  add_2_calendar: ^3.0.1
  timezone: ^0.10.1
  uuid: ^4.4.0
  url_launcher: ^6.3.0
  cupertino_icons: ^1.0.6
  image_picker: ^1.1.2
  share_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/pictogramas/
    - assets/audio/bell.mp3